behaviors:
  WaistTrackerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 4.0e-3
      epsilon: 0.2
      lambd: 0.90
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      use_recurrent: true
      vis_encode_type: simple
      memory:
        memory_size: 32
        sequence_length: 8
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 50000
    threaded: true